name: "bluebell"
mode: "dev"
version: "v0"
port: 8080
start_time: "2025-01-11"
machine_id: 1

auth:
  jwt_expire: 8760
log:
  level: "debug"
  filename: "bluebell.log"
  max_size: 200
  max_age: 30
  max_backups: 7
mysql:
  host: "127.0.0.1"
  port: 13306
  user: "root"
  password: "root1234"
  dbname: "bluebell"
  max_open_conns: 200
  max_idle_conns: 50
redis:
  host: "127.0.0.1"
  port: 6379
  password: ""
  db: 0
  pool_size: 100

mongo:
  host: "127.0.0.1"
  port: 27017
  user: "root"
  password: ""
  dbname: "bluebell"
